.ALIASES
R_R1            R1(1=N000811 2=N00159 ) CN @HW4.SCHEMATIC1(sch_1):INS71@ANALOG.R.Normal(chips)
V_V2            V2(+=N00159 -=0 ) CN @HW4.SCHEMATIC1(sch_1):INS141@SOURCE.VDC.Normal(chips)
Q_Q1            Q1(c=N000811 b=N00239 e=0 ) CN @HW4.SCHEMATIC1(sch_1):INS342@BREAKOUT.QbreakN.Normal(chips)
V_V3            V3(+=N00239 -=0 ) CN @HW4.SCHEMATIC1(sch_1):INS786@SOURCE.VDC.Normal(chips)
.ENDALIASES
