.ALIASES
M_M2            M2(d=N00951 g=N00760 s=0 s=0 ) CN @1-B.SCHEMATIC1(sch_1):INS615@BREAKOUT.MbreakN3.Normal(chips)
V_V1            V1(+=N01218 -=0 ) CN @1-B.SCHEMATIC1(sch_1):INS677@SOURCE.VDC.Normal(chips)
M_M4            M4(d=N00951 g=N00951 s=N01218 s=N01218 ) CN @1-B.SCHEMATIC1(sch_1):INS919@BREAKOUT.MbreakP3.Normal(chips)
V_V2            V2(+=N00760 -=0 ) CN @1-B.SCHEMATIC1(sch_1):INS1339@SOURCE.VSIN.Normal(chips)
.ENDALIASES
