.ALIASES
M_M1            M1(d=N00130 g=N00189 s=N00126 s=N00126 ) CN @2-B.SCHEMATIC1(sch_1):INS28@BREAKOUT.MbreakN3.Normal(chips)
V_V1            V1(+=N00134 -=0 ) CN @2-B.SCHEMATIC1(sch_1):INS69@SOURCE.VDC.Normal(chips)
R_R1            R1(1=N00130 2=N00134 ) CN @2-B.SCHEMATIC1(sch_1):INS94@ANALOG.R.Normal(chips)
R_R2            R2(1=0 2=N00126 ) CN @2-B.SCHEMATIC1(sch_1):INS110@ANALOG.R.Normal(chips)
V_V2            V2(+=N00189 -=0 ) CN @2-B.SCHEMATIC1(sch_1):INS270@SOURCE.VSIN.Normal(chips)
.ENDALIASES
