.ALIASES
V_VX            VX(+=N00129 -=0 ) CN @D2.SCHEMATIC1(sch_1):INS40@SOURCE.VDC.Normal(chips)
M_M2            M2(d=N00840 g=N00243 s=0 s=0 ) CN @D2.SCHEMATIC1(sch_1):INS91@BREAKOUT.MbreakN3.Normal(chips)
V_V1            V1(+=N00185 -=0 ) CN @D2.SCHEMATIC1(sch_1):INS159@SOURCE.VDC.Normal(chips)
V_V2            V2(+=N00243 -=0 ) CN @D2.SCHEMATIC1(sch_1):INS217@SOURCE.VDC.Normal(chips)
M_M3            M3(d=N00129 g=N00185 s=N00840 s=N00840 ) CN @D2.SCHEMATIC1(sch_1):INS792@BREAKOUT.MbreakN3.Normal(chips)
.ENDALIASES
