.ALIASES
D_ID2           ID2(1=N00119 2=N01824 ) CN @2.SCHEMATIC1(sch_1):INS65@BREAKOUT.Dbreak.Normal(chips)
V_Vs            Vs(+=N00119 -=N02700 ) CN @2.SCHEMATIC1(sch_1):INS1631@SOURCE.VSIN.Normal(chips)
C_C1            C1(1=0 2=N01824 ) CN @2.SCHEMATIC1(sch_1):INS1742@ANALOG.C.Normal(chips)
R_Vout          Vout(1=0 2=N01824 ) CN @2.SCHEMATIC1(sch_1):INS1808@ANALOG.R.Normal(chips)
D_D2            D2(1=0 2=N00119 ) CN @2.SCHEMATIC1(sch_1):INS2521@BREAKOUT.Dbreak.Normal(chips)
D_D3            D3(1=0 2=N02700 ) CN @2.SCHEMATIC1(sch_1):INS2618@BREAKOUT.Dbreak.Normal(chips)
D_ID3           ID3(1=N02700 2=N01824 ) CN @2.SCHEMATIC1(sch_1):INS2656@BREAKOUT.Dbreak.Normal(chips)
.ENDALIASES
